server:
  port: 4444

spring:
  application:
    name: gateway-server


eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://173.17.0.2:8761/eureka}
  instance:
    preferIpAddress: true
